In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [7]:
df = pd.read_excel("amazon.csv.xlsx")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,â‚¹399,"â‚¹1,099",0.64,4.2,24269.0,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,â‚¹199,â‚¹349,0.43,4,43994.0,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,â‚¹199,"â‚¹1,899",0.90,3.9,7928.0,ã€ Fast Charger& Data Syncã€‘-With built-in s...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,â‚¹329,â‚¹699,0.53,4.2,94363.0,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,â‚¹154,â‚¹399,0.61,4.2,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [8]:
print("Dataset Shape:", df.shape)

df.info()
df.describe()
df.columns

Dataset Shape: (1465, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   float64
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: float64(2), object(14)
memory usage: 183.3+ KB

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='object')

In [9]:
df.drop_duplicates(inplace=True)
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (1465, 16)

In [10]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [11]:
#removing certain columns which are not useful for analytics dashboards

In [12]:
columns_to_drop = ['img_link','product_link','user_id','user_name','review_id','review_content']

df.drop(columns=columns_to_drop, inplace=True, errors='ignore')
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'review_title'],
      dtype='object')

In [13]:
#Cleaning the discounted and actual price - columns to perform calculations

In [14]:
df['discounted_price'] = df['discounted_price'].replace('[^0-9.]', '', regex=True)
df['actual_price'] = df['actual_price'].replace('[^0-9.]', '', regex=True)

df['discounted_price'] = df['discounted_price'].astype(float)
df['actual_price'] = df['actual_price'].astype(float)

In [15]:
#Cleaning the rating count

In [16]:
df['rating_count'] = df['rating_count'].replace(',', '', regex=True)
df['rating_count'] = df['rating_count'].astype(float)

In [17]:
#Cleaning rating columns

In [18]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['rating_count'] = df['rating_count'].replace(',', '', regex=True)
df['rating_count'] = pd.to_numeric(df['rating_count'], errors='coerce')

In [19]:
df[['rating','rating_count']].head()

   rating  rating_count
0     4.2       24269.0
1     4.0       43994.0
2     3.9        7928.0
3     4.2       94363.0
4     4.2       16905.0

In [20]:
df['main_category'] = df['category'].str.split('|').str[0]

In [21]:
#Estimating revenue based on rating count as real sales quantity is not available

In [22]:
df['estimated_revenue'] = df['discounted_price'] * df['rating_count']

In [23]:
#EXPLORATORY DATA ANALYSIS ON :

In [24]:
#1. TOP CATEGORIES BY REVENUE

In [25]:
category_revenue = df.groupby('main_category')['estimated_revenue'].sum().sort_values(ascending=False)
print(category_revenue.head(10))

main_category
Electronics              5.917975e+10
Computers&Accessories    6.354569e+09
Home&Kitchen             6.264336e+09
MusicalInstruments       6.445808e+07
OfficeProducts           4.578673e+07
Health&PersonalCare      3.293037e+06
Car&Motorbike            2.615002e+06
HomeImprovement          2.587190e+06
Toys&Games               2.380050e+06
Name: estimated_revenue, dtype: float64

In [26]:
#2. TOP PRODUCTS BY REVENUE

In [27]:
top_products = df.sort_values(by='estimated_revenue', ascending=False).head(10)
print(top_products[['product_name','main_category','estimated_revenue']])

                                          product_name main_category  \
370  Redmi 9 Activ (Carbon Black, 4GB RAM, 64GB Sto...   Electronics
566  Redmi 9A Sport (Coral Green, 3GB RAM, 32GB Sto...   Electronics
371  Redmi 9A Sport (Coral Green, 2GB RAM, 32GB Sto...   Electronics
473  Redmi 9A Sport (Carbon Black, 2GB RAM, 32GB St...   Electronics
124  Redmi 126 cm (50 inches) 4K Ultra HD Android S...   Electronics
72   Redmi 108 cm (43 inches) 4K Ultra HD Android S...   Electronics
568  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...   Electronics
332  MI 138.8 cm (55 inches) 5X Series 4K Ultra HD ...   Electronics
91   OnePlus 108 cm (43 inches) Y Series Full HD Sm...   Electronics
197  MI 108 cm (43 inches) 5A Series Full HD Smart ...   Electronics

     estimated_revenue
370       2.667292e+09
566       2.353426e+09
371       2.039620e+09
473       2.039594e+09
124       1.492809e+09
72        1.221381e+09
568       1.055742e+09
332       9.988227e+08
91        8.724401e+08
197       8.209672e+08

In [31]:
#3. AVERAGE RATING BY CATEGORY

In [32]:
category_rating = df.groupby('main_category')['rating'].mean().sort_values(ascending=False)
print(category_rating.head(10))

main_category
OfficeProducts           4.309677
Toys&Games               4.300000
HomeImprovement          4.250000
Computers&Accessories    4.154967
Electronics              4.081749
Home&Kitchen             4.040716
Health&PersonalCare      4.000000
MusicalInstruments       3.900000
Car&Motorbike            3.800000
Name: rating, dtype: float64

In [ ]:
#Verifying the final structure of the now cleaned dataset

In [33]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1464 non-null   float64
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   object
 9   review_title         1465 non-null   object
 10  main_category        1465 non-null   object
 11  estimated_revenue    1463 non-null   float64
dtypes: float64(6), object(6)
memory usage: 137.5+ KB

In [34]:
#Cleaned dataset exported for tableau dashboard

In [35]:
df.to_excel("amazon_sales_cleaned.xlsx", index=False)